# Generated by Django 6.0.7 on 2026-07-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('TopicID', models.AutoField(primary_key=True, serialize=False)),
                ('TopicName', models.CharField(max_length=200)),
                ('TopicDescription', models.TextField()),
                ('TopicPublishingDate', models.DateField()),
            ],
            options={
                'ordering': ['-TopicPublishingDate'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CommenterName', models.CharField(max_length=150)),
                ('CommentText', models.TextField()),
                ('TopicID', models.ForeignKey(db_column='TopicID', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.topic')),
            ],
            options={
                'ordering': ['CommentNumber'],
            },
        ),
    ]
